FROM jupyter/scipy-notebook:2023-06-01

COPY requirements.txt /tmp/

RUN pip install --upgrade pip \
    && pip install -r /tmp/requirements.txt

COPY . /app
WORKDIR /app

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root", "--no-browser"]